/**
 * Relational Structure for Bible Verses separating reference from content.
 * 
 * This structure adheres to the Catholic Canon (73 Books).
 */

export interface BiblicalStructure {
  /**
   * Unique anchor ID for the verse.
   * Computed deterministically, e.g., (book_id * 1000000) + (chapter_number * 1000) + verse_number
   */
  id: number;
  
  /**
   * Book ID (1-73 for the Catholic Canon)
   */
  book_id: number;
  
  /**
   * Chapter Number
   */
  chapter_number: number;
  
  /**
   * Verse Number
   */
  verse_number: number;
}

export type VersionTag = 'en_dr' | 'la_vg' | 'nl_pc';

export interface BibleTranslation {
  /**
   * Unique ID for this specific translation text entry
   */
  id: number;
  
  /**
   * Foreign key to BiblicalStructure.id
   */
  structure_id: number;
  
  /**
   * Language version tag
   */
  version_tag: VersionTag;
  
  /**
   * The actual text content in the target language
   */
  text_content: string;
}

/**
 * Mapping Logic: Standardized numbering system
 * 
 * Generates a unique, language-agnostic structure_id for any given Biblical anchor.
 * Ensures Verse X in Book Y is always mapped to the same structure_id regardless of language.
 * 
 * @param bookId Numeric ID of the book (1-73)
 * @param chapter Chapter number
 * @param verse Verse number
 * @returns Deterministic structure_id
 */
export const generateStructureId = (bookId: number, chapter: number, verse: number): number => {
  return (bookId * 1000000) + (chapter * 1000) + verse;
};

/**
 * Generates the anchor object for a given verse.
 * 
 * @param bookId Numeric ID of the book (1-73)
 * @param chapter Chapter number
 * @param verse Verse number
 * @returns BiblicalStructure record
 */
export const createBiblicalStructure = (bookId: number, chapter: number, verse: number): BiblicalStructure => {
  return {
    id: generateStructureId(bookId, chapter, verse),
    book_id: bookId,
    chapter_number: chapter,
    verse_number: verse
  };
};

/**
 * Initializes a mapping for a specific Bible version translation
 * 
 * @param structure_id The anchor ID generated by `generateStructureId`
 * @param text The verse text
 * @param version The tag: 'en_dr' (English), 'la_vg' (Latin), or 'nl_pc' (Dutch)
 */
export const createTranslationMapping = (
  structure_id: number,
  text: string,
  version: VersionTag
): BibleTranslation => {
  // Use a hash-like ID for the translation row, combining structure_id and the version tag
  // In a real database this would be an auto-increment or uniquely generated UUID
  let uniqueStringId = `${structure_id}-${version}`;
  let translationId = 0;
  for (let i = 0; i < uniqueStringId.length; i++) {
    translationId = Math.imul(31, translationId) + uniqueStringId.charCodeAt(i) | 0;
  }
  
  return {
    id: Math.abs(translationId),
    structure_id,
    version_tag: version,
    text_content: text
  };
};

/**
 * Example usage representing how the three version mappings would be initialized:
 */
export const exampleInitialization = () => {
  // E.g., Genesis 1:1 (Book 1)
  const anchor = createBiblicalStructure(1, 1, 1);
  
  const translations = [
    createTranslationMapping(anchor.id, "In the beginning God created heaven, and earth.", "en_dr"),
    createTranslationMapping(anchor.id, "In principio creavit Deus caelum et terram.", "la_vg"),
    createTranslationMapping(anchor.id, "In het begin schiep God de hemel en de aarde.", "nl_pc")
  ];
  
  return { anchor, translations };
};
